# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Todo;

user1 = User.create!({ name: "ben", email: "ben@test.com", user_photo: "https://res.cloudinary.com/benlovesplants89/image/upload/v1616458245/Plant_Track/ben_zmpxmk.jpg", password: "password", admin: true })
user2 = User.create!({ name: "peter", email: "peter@test.com", user_photo: "https://res.cloudinary.com/benlovesplants89/image/upload/v1616442942/Plant_Track/peter_kor89f.jpg", password: "password" })
user3 = User.create!({ name: "kevin", email: "kevin@test.com", user_photo: "https://res.cloudinary.com/benlovesplants89/image/upload/v1616442942/Plant_Track/kevin_eqrmm5.jpg", password: "password" })

plant1 = Plant.create!({ scientific_name: "P. erubescens", common_name: "Pink Princess Philodendron", plant_family: "Philodendron", description: "Black-leaf philodendron with hot pink variegation.", light: "High", temperature: "65-85", humidity: "High", water_freq: "Low", soil_type: "Ariod", difficulty_level: "Medium" })
plant2 = Plant.create!({ scientific_name: "scindapsus treubii", common_name: "scindapsus treubii", plant_family: "Scindapsus", description: "These plants have a smooth stem and oval or heart-shaped leaves of green color with hints of silver. This is where the name “Scindapsus Moonlight” comes from.  These leaves can grow as long as 12 to 60 centimeters and are the primary attraction of the plant with their beautiful, satin finish. The leaves grow to their full potential if given strong, rigid support such as a stalk or a bamboo stick.", light: "Medium", temperature: "60-90", humidity: "Medium", water_freq: "Low", soil_type: "Indoor Plant", difficulty_level: "Easy" })
plant3 = Plant.create!({ scientific_name: "Aeschynanthus marmoratus", common_name: "Zebra Basket Vine", plant_family: "Gesneriaceae", description: "Dark green trailing house plant with oval shaped leaves with wonderful detailing in purple. Perfect for hanging baskets.", light: "", temperature: "70-90", humidity: "High", water_freq: "Medium", soil_type: "African Violet", difficulty_level: "High" })
plant4 = Plant.create!({ scientific_name: "Beaucarnea recurvata", common_name: "Pony Tail Palm", plant_family: "Asparagaceae", description: "Beaucarneas are curious plants with a heavily swollen base and grass like foliage giving it a unique appearance. The the stem is used to store water which is a great help to those of us that forget the odd watering or are absent for a week or so. From 8 foot specimens to dinky infants these plants are invaluable in a bright room. Definitely in the top 5 easiest houseplants list!", light: "bright", temperature: "60-90", humidity: "Medium", water_freq: "Low", soil_type: "Standard Potting", difficulty_level: "Easy" })
plant5 = Plant.create!({ scientific_name: "Calathea lancifolia", common_name: "Rattlesnake plant", plant_family: "Arrowroots", description: "Another beautiful Calathea from Brazil. Very bold markings on long elegant leaves.", light: "Low", temperature: "60-80", humidity: "Medium", water_freq: "Medium", soil_type: "Jungle Floor", difficulty_level: "Medium" })
plant6 = Plant.create!({ scientific_name: "Ceropegia woodii", common_name: "String of Hearts", plant_family: "Asclepidia", description: "This stunning evergreen succulent is a trailing vine that can spread up to 4 meters in length and 10cm in height. The leaves are shaped like hearts (hence the name) and are deep green with variegated silver markings. The stems are wire-thin and pinkish.Discovered in 1881 by John Medley Wood of Durban Botanic Gardens hanging from rocks in Natal at an altitude of 1800 feet! He sent it to Kew and its trailing habit and tolerance of neglect led it to becoming an ideal plant for hanging pots.It also has water storing tubers, making it virtually drought-resistant. Very easy to grow on from cuttings.", light: "High", temperature: "65-90", humidity: "Medium", water_freq: "Low", soil_type: "Fast Draing/Fungle Floor", difficulty_level: "easy" })
plant7 = Plant.create!({ scientific_name: "Thaumatophyllum bipinnatifidum", common_name: "Philodendron 'Xanadu'", plant_family: "Arums", description: "An exotic houseplant with deeply dissected dark green leaves. Unlike many Philodendrons this is not a climber but will grow into a medium sized shrub. Fantastic in a large room, hallway or bathroom it will add a piece of jungle to any home.", light: "High", temperature: "65-90", humidity: "Medium", water_freq: "Low", soil_type: "ariod", difficulty_level: "Easy" })
plant8 = Plant.create!({ scientific_name: "Peperomia caperata", common_name: "Peperomia caperata 'Rosso', Radiator Plant", plant_family: "Piperaceae", description: "Bright, colourful and like all the pepperomias very very interesting (There are over 1000 species!). The burgundy red of the leaves of rosso is shown in the light underside and the dark top, otherworldy flower spires top off this lovely slow-growing houseplant.", light: "Low", temperature: "60-85", humidity: "Medium", water_freq: "Low", soil_type: "well draining", difficulty_level: "Easy" })
plant9 = Plant.create!({ scientific_name: "Pilea peperomiodes", common_name: "Chinese Money Plant", plant_family: "Urticaceae", description: "his is an amazingly interesting plant as it has such unique circular, shiny, dark green leaves. One of the few houseplants made popular by people sharing the young offsetts rather than comercial horticulture. Also called the UFO plant!", light: "Medium", temperature: "55-85", humidity: "Medium", water_freq: "Low", soil_type: "Forest floor, well-draing", difficulty_level: "Easy" })
plant10 = Plant.create!({ scientific_name: "Tradescantia zebrina", common_name: "Tradescantia zebrina", plant_family: "Spiderworts", description: "This really is a colourful specimen, striking leaves of purple, shades of green and silver. The trailing habit of this plant gives a cascade of colour to any environment, maximizing on limited avaible space.", light: "Medium", temperature: "65-90", humidity: "Medium", water_freq: "Low", soil_type: "", difficulty_level: "Easy" })
plant11 = Plant.create!({ scientific_name: "Zamioculcas zamiifolia 'Raven'", common_name: "ZZ Raven", plant_family: "Arums", description: "Black is not found hardly at all in nature and the breeding of black plants is considered the holy grail of growers all over the world. This ZZ plant is very very close to a true black when the leaves mature. Stunning and very very unusual. Easy to look after but be careful not to over water.", light: "Low", temperature: "60-85", humidity: "Medium", water_freq: "Low", soil_type: "Well Draining", difficulty_level: "Easy" })
plant12 = Plant.create!({ scientific_name: "Philodendron standleyana", common_name: "Monstera Cobra", plant_family: "Monstera", description: "Gorgeous speckled variegation on every single leaf, with blotches of creamy white creating highlights up the tower of the plant. The spearhead shaped leaves create plenty of gaps in the foliage to see through, meaning the depth of the plant is an absolute wonder to look at.", light: "High", temperature: "70-90", humidity: "High", water_freq: "Low", soil_type: "Ariod", difficulty_level: "Medium" })
plant13 = Plant.create!({ scientific_name: "Aeschynanthus pulcher", common_name: "Lipstick plant", plant_family: "Gesneriaceae", description: "A very easy to look after flowering trailer. Dark green glossy leaves and a stunning bight red flower. Needs good light to get the best flowering.", light: "Medium", temperature: "65-85", humidity: "Medium", water_freq: "Medium", soil_type: "African Violet", difficulty_level: "easy" })
plant14 = Plant.create!({ scientific_name: "Begonia maculata 'Wightii'", common_name: "Spotted begonia", plant_family: "Begoniaceae", description: "This is not your average hanging basket begonia but a tropical talking point! The long leaves have a lovely red backing as well as the striking symetrical patterning on the front. Warmth is the key with these plants this along with good light they will thrive.", light: "Hight", temperature: "70-85", humidity: "Medium", water_freq: "Medium", soil_type: "Well draining - Moist", difficulty_level: "High - Medium" })
plant15 = Plant.create!({ scientific_name: "Fittonia albivenis", common_name: "Nerve Plant", plant_family: "Acanthaceae", description: "Also known as the Mosaic Plant, this gorgeously vibrant and colourful vivarium is a great addition to any terrarium. Also known as the Mosaic Plant, this gorgeously vibrant and colourful vivarium is a great addition to any terrarium.If left to grow, the spread of thick leaves will expand out and present an attractive plane of brilliant colour and shine, with vertical growth of up to 20cm from the top of the pot.", light: "Medium", temperature: "65-90", humidity: "Medium", water_freq: "Medium", soil_type: "Standard Houseplant", difficulty_level: "Medium" })
plant16 = Plant.create!({ scientific_name: "Epipremnum aureum Variegata", common_name: "Marble Queen", plant_family: "Monsteroideae", description: "In fitting with the recent national obsession with variegated climbing plants, this is a wonderful addition to our home grown collection of Epipremnums. Really easy to grow and fantastic at cleaning the air, the marbling on this plant is so varied and wonderful that each plant has its own unique character and identity.", light: "Medium", temperature: "60-95", humidity: "Medium", water_freq: "Low", soil_type: "Standard Houseplant", difficulty_level: "Easy" })
plant17 = Plant.create!({ scientific_name: "Monstera deliciosa 'Albo-Variegata", common_name: "Albo Monstera", plant_family: "Monsteroideae", description: "White Variegated Monstera has leaves 13-18” wide with large holes resembling Swiss cheese (some people call it Swiss Cheese Plant). Each leaf is unique with no two the same. The irregular cream-and-green variegation creates some leaves that are nearly fully white with green markings and other leaves are green with white marbling. Aerial roots anchor it to a trellis, moss pole or wall. In its native habitat, it’s an understory plant that climbs up tropical trees. Mature plants produce breadfruit, an 8-10” long cone, that takes a year to mature into an edible fruit.", light: "High", temperature: "70-90", humidity: "High", water_freq: "Low", soil_type: "Aroid", difficulty_level: "High" })
plant18 = Plant.create!({ scientific_name: "Ficus lyrata", common_name: "Fiddle leaf fig", plant_family: "Mulberry family", description: " The Fiddle leaf fig, glorious and exotic indoor tree . Branches will grow from the leaf bases in time creating a wonderfully tropical specimen. Unbelievably fashionable its 'the' plant of the decade, so far!", light: "High", temperature: "70-85", humidity: "High", water_freq: "Low", soil_type: "Fiddle Leaf Fig Specialty Soil", difficulty_level: "High" })
plant19 = Plant.create!({ scientific_name: "Spathiphyllum wallisii", common_name: "Peace Lilly", plant_family: "Arums", description: "If there was to be a top ten most loved houseplants then we would bet on the Peace Lily being if not top very close. Large dark green leaves and its simple white spathe flower give it a look all to itself. We have afew varieties here the video below runs through some of them.", light: "Medium", temperature: "65-90", humidity: "Medium", water_freq: "Medium", soil_type: "Standard Houseplant", difficulty_level: "Easy" })
plant20 = Plant.create!({ scientific_name: "Oxalis triangularis purpurea", common_name: "False Shamrock", plant_family: "Wood sorrels", description: "An easy to care for compact indoor perennial plant with an attractive display of burgandy-red clover-like foliage from spring to autumn and edible, tubular pink flowers throughout the summer. A rare and sought-after houseplant which has risen in popularity due to recent High exposures in the media. The leaves have a fascinating photonastic response, closing at night and opening in the morning. At night, neatly folded, the leaves looks like a cluster of purple butterflies. Incredible long-lived. The plant's history can be traced back to St. Patrick, who used the leaves to explain the concept of the Holy Trinity to the Irish. They are not Irish natives however, instead hailing from several countries in South America. They are also make great gifts and are popular heirloom plants, passed down from generation to generation within a family.", light: "Medium", temperature: "65-85", humidity: "Medium", water_freq: "Medium", soil_type: "Standard Houseplant", difficulty_level: "Easy" })
# plant21 = Plant.create!({scientific_name:"", common_name:"",plant_family:"", description:"", light: "", temperature: "", humidity: "", water_freq: "",soil_type:"",difficulty_level:""})
# plant22 = Plant.create!({scientific_name:"", common_name:"",plant_family:"", description:"", light: "", temperature: "", humidity: "", water_freq: "",soil_type:"",difficulty_level:""})
# plant23 = Plant.create!({scientific_name:"", common_name:"",plant_family:"", description:"", light: "", temperature: "", humidity: "", water_freq: "",soil_type:"",difficulty_level:""})

user_plant1 = UserPlant.create!({ user_id: user1.id, plant_id: plant1.id, date_aquired: DateTime.new(2020, 2, 3) })
user_plant2 = UserPlant.create!({ user_id: user2.id, plant_id: plant1.id, date_aquired: DateTime.new(2020, 2, 3) })
user_plant3 = UserPlant.create!({ user_id: user2.id, plant_id: plant10.id, date_aquired: DateTime.new(2021, 2, 10) })
user_plant4 = UserPlant.create!({ user_id: user3.id, plant_id: plant3.id, date_aquired: DateTime.new(2020, 2, 3) })
user_plant5 = UserPlant.create!({ user_id: user2.id, plant_id: plant1.id, date_aquired: DateTime.new(2021, 1, 22) })
user_plant6 = UserPlant.create!({ user_id: user2.id, plant_id: plant19.id, date_aquired: DateTime.new(2021, 1, 8) })
user_plant7 = UserPlant.create!({ user_id: user3.id, plant_id: plant14.id, date_aquired: DateTime.new(2020, 8, 3) })
user_plant8 = UserPlant.create!({ user_id: user3.id, plant_id: plant14.id, date_aquired: DateTime.new(2020, 5, 9) })
user_plant9 = UserPlant.create!({ user_id: user1.id, plant_id: plant20.id, date_aquired: DateTime.new(2019, 2, 12) })
user_plant10 = UserPlant.create!({ user_id: user2.id, plant_id: plant6.id, date_aquired: DateTime.new(2018, 1, 4) })
user_plant11 = UserPlant.create!({ user_id: user2.id, plant_id: plant14.id, date_aquired: DateTime.new(2020, 5, 5) })
user_plant12 = UserPlant.create!({ user_id: user2.id, plant_id: plant3.id, date_aquired: DateTime.new(2020, 10, 31) })
user_plant13 = UserPlant.create!({ user_id: user2.id, plant_id: plant2.id, date_aquired: DateTime.new(2020, 8, 1) })
user_plant14 = UserPlant.create!({ user_id: user2.id, plant_id: plant1.id, date_aquired: DateTime.new(2020, 6, 20) })
user_plant15 = UserPlant.create!({ user_id: user2.id, plant_id: plant12.id, date_aquired: DateTime.new(2020, 11, 13) })
user_plant16 = UserPlant.create!({ user_id: user2.id, plant_id: plant17.id, date_aquired: DateTime.new(2021, 1, 13) })
user_plant17 = UserPlant.create!({ user_id: user2.id, plant_id: plant13.id, date_aquired: DateTime.new(2021, 3, 5) })
# user_plant11 = UserPlant.create!({user_id: user1.id,plant_id: plant1.id, date_aquired: ,})

Watering.create!({ user_plant_id: user_plant1.id, date: DateTime.new(2021, 2, 3) })
Watering.create!({ user_plant_id: user_plant1.id, date: DateTime.new(2021, 2, 10) })
Watering.create!({ user_plant_id: user_plant1.id, date: DateTime.new(2021, 3, 1) })
Watering.create!({ user_plant_id: user_plant7.id, date: DateTime.new(2021, 1, 3) })
Watering.create!({ user_plant_id: user_plant7.id, date: DateTime.new(2021, 2, 15) })
Watering.create!({ user_plant_id: user_plant11.id, date: DateTime.new(2021, 2, 3) })
Watering.create!({ user_plant_id: user_plant10.id, date: DateTime.new(2021, 2, 3) })
Watering.create!({ user_plant_id: user_plant12.id, date: DateTime.new(2021, 2, 3) })
Watering.create!({ user_plant_id: user_plant3.id, date: DateTime.new(2021, 2, 3) })
Watering.create!({ user_plant_id: user_plant3.id, date: DateTime.new(2021, 2, 15) })
Watering.create!({ user_plant_id: user_plant5.id, date: DateTime.new(2021, 1, 5) })
Watering.create!({ user_plant_id: user_plant5.id, date: DateTime.new(2021, 1, 7) })
Watering.create!({ user_plant_id: user_plant6.id, date: DateTime.new(2021, 1, 9) })
Watering.create!({ user_plant_id: user_plant6.id, date: DateTime.new(2021, 2, 20) })
Watering.create!({ user_plant_id: user_plant13.id, date: DateTime.new(2020, 12, 30) })
Watering.create!({ user_plant_id: user_plant14.id, date: DateTime.new(2021, 2, 25) })
Watering.create!({ user_plant_id: user_plant15.id, date: DateTime.new(2021, 1, 13) })
Watering.create!({ user_plant_id: user_plant12.id, date: DateTime.new(2021, 3, 1) })
Watering.create!({ user_plant_id: user_plant2.id, date: DateTime.new(2021, 2, 5) })
Watering.create!({ user_plant_id: user_plant12.id, date: DateTime.new(2021, 3, 5) })
Watering.create!({ user_plant_id: user_plant2.id, date: DateTime.new(2021, 2, 20) })
Watering.create!({ user_plant_id: user_plant12.id, date: DateTime.new(2020, 7, 5) })
Watering.create!({ user_plant_id: user_plant2.id, date: DateTime.new(2021, 3, 1) })
Watering.create!({ user_plant_id: user_plant16.id, date: DateTime.new(2021, 3, 15) })
Watering.create!({ user_plant_id: user_plant17.id, date: DateTime.new(2021, 3, 10) })
Watering.create!({ user_plant_id: user_plant11.id, date: DateTime.new(2021, 3, 18) })

location1 = Location.create!({ name: "Living Room", description: "High Light Low Humidity" })
location2 = Location.create!({ name: "Bedroom1", description: "Low Light Low Humidity" })
location3 = Location.create!({ name: "Basment", description: "Low Light High Humdidty" })
location4 = Location.create!({ name: "Kitchen", description: "Medium Light, High Humdity, High Heat" })
location5 = Location.create!({ name: "Bathroom", description: "Low Light High Humidity" })
# location1 = Location.create!({name: "",description: ""})

LocationUserPlant.create!({ user_plant_id: user_plant1.id, location_id: location1.id, date: DateTime.new(2020, 2, 3) })
LocationUserPlant.create!({ user_plant_id: user_plant1.id, location_id: location2.id, date: DateTime.new(2021, 2, 3) })
LocationUserPlant.create!({ user_plant_id: user_plant3.id, location_id: location2.id, date: DateTime.new(2021, 2, 3) })
LocationUserPlant.create!({ user_plant_id: user_plant3.id, location_id: location3.id, date: DateTime.new(2021, 1, 30) })
LocationUserPlant.create!({ user_plant_id: user_plant4.id, location_id: location4.id, date: DateTime.new(2021, 2, 17) })
LocationUserPlant.create!({ user_plant_id: user_plant9.id, location_id: location4.id, date: DateTime.new(2021, 1, 18) })
LocationUserPlant.create!({ user_plant_id: user_plant13.id, location_id: location5.id, date: DateTime.new(2021, 3, 3) })

Rating.create!({ user_id: user1.id, plant_id: plant1.id, liked: true })
Rating.create!({ user_id: user2.id, plant_id: plant1.id, liked: false })
Rating.create!({ user_id: user2.id, plant_id: plant2.id, liked: true })
Rating.create!({ user_id: user2.id, plant_id: plant3.id, liked: true })
Rating.create!({ user_id: user2.id, plant_id: plant4.id, liked: true })
Rating.create!({ user_id: user2.id, plant_id: plant5.id, liked: false })
Rating.create!({ user_id: user2.id, plant_id: plant6.id, liked: false })
Rating.create!({ user_id: user2.id, plant_id: plant7.id, liked: true })
Rating.create!({ user_id: user2.id, plant_id: plant8.id, liked: false })
Rating.create!({ user_id: user2.id, plant_id: plant9.id, liked: false })
Rating.create!({ user_id: user3.id, plant_id: plant1.id, liked: true })
Rating.create!({ user_id: user3.id, plant_id: plant2.id, liked: true })
Rating.create!({ user_id: user3.id, plant_id: plant3.id, liked: false })
Rating.create!({ user_id: user3.id, plant_id: plant4.id, liked: false })
Rating.create!({ user_id: user3.id, plant_id: plant5.id, liked: false })
# Rating.create!({user_id: user1.id, plant_id: plant1.id, liked: ,})

Picture.create!({ plant_id: plant1.id, user_id: user1.id, img_url: "https://res.cloudinary.com/benlovesplants89/image/upload/v1614908736/Plant_Track/PinkPrincess1_gyvj13.jpg" })
Picture.create!({ plant_id: plant2.id, user_id: user1.id, img_url: "https://res.cloudinary.com/benlovesplants89/image/upload/v1614908737/Plant_Track/scindapsus_treubii2_xikgrj.jpg" })
Picture.create!({ plant_id: plant3.id, user_id: user1.id, img_url: "https://res.cloudinary.com/benlovesplants89/image/upload/v1614908738/Plant_Track/Zebra_Basket_Vine1_g4wvll.jpg" })
Picture.create!({ plant_id: plant4.id, user_id: user1.id, img_url: "https://res.cloudinary.com/benlovesplants89/image/upload/v1614908737/Plant_Track/Pony_Tail_Palm1_bfduin.webp" })
Picture.create!({ plant_id: plant5.id, user_id: user1.id, img_url: "https://res.cloudinary.com/benlovesplants89/image/upload/v1614908734/Plant_Track/Calathea_lancifolia_sxhdsz.jpg" })
Picture.create!({ plant_id: plant6.id, user_id: user1.id, img_url: "https://res.cloudinary.com/benlovesplants89/image/upload/v1614908736/Plant_Track/Ceropegia_woodii_wwhfqt.jpg" })
Picture.create!({ plant_id: plant7.id, user_id: user1.id, img_url: "https://res.cloudinary.com/benlovesplants89/image/upload/v1614908737/Plant_Track/Philodendron_Xanadu_hnmapj.jpg" })
Picture.create!({ plant_id: plant8.id, user_id: user1.id, img_url: "https://res.cloudinary.com/benlovesplants89/image/upload/v1614908736/Plant_Track/Peperomia_caperata_yiriky.jpg" })
Picture.create!({ plant_id: plant9.id, user_id: user1.id, img_url: "https://res.cloudinary.com/benlovesplants89/image/upload/v1614908736/Plant_Track/Pilea_peperomiodes_lf2un4.jpg" })
Picture.create!({ plant_id: plant10.id, user_id: user1.id, img_url: "https://res.cloudinary.com/benlovesplants89/image/upload/v1614908737/Plant_Track/Tradescantia_zebrina_ms6bpa.jpg" })
Picture.create!({ plant_id: plant11.id, user_id: user1.id, img_url: "https://res.cloudinary.com/benlovesplants89/image/upload/v1614908738/Plant_Track/ZZ_Raven_pb0cpt.jpg" })
Picture.create!({ plant_id: plant12.id, user_id: user1.id, img_url: "https://res.cloudinary.com/benlovesplants89/image/upload/v1614908736/Plant_Track/Philodendron_standleyana_xtqevp.jpg" })
Picture.create!({ plant_id: plant13.id, user_id: user1.id, img_url: "https://res.cloudinary.com/benlovesplants89/image/upload/v1614908736/Plant_Track/Lipstick_plant_fsczm4.jpg" })
Picture.create!({ plant_id: plant14.id, user_id: user1.id, img_url: "https://res.cloudinary.com/benlovesplants89/image/upload/v1614908735/Plant_Track/Begonia_maculata_wightii_fcfsv4.jpg" })
Picture.create!({ plant_id: plant15.id, user_id: user1.id, img_url: "https://res.cloudinary.com/benlovesplants89/image/upload/v1614908735/Plant_Track/Never_plant_nvuj9f.jpg" })
Picture.create!({ plant_id: plant16.id, user_id: user1.id, img_url: "https://res.cloudinary.com/benlovesplants89/image/upload/v1614908734/Plant_Track/Epipremnum_aureum_Variegata_gnneej.jpg" })
Picture.create!({ plant_id: plant17.id, user_id: user1.id, img_url: "https://res.cloudinary.com/benlovesplants89/image/upload/v1614908735/Plant_Track/Monstera_Albo_eudaib.jpg" })
Picture.create!({ plant_id: plant18.id, user_id: user1.id, img_url: "https://res.cloudinary.com/benlovesplants89/image/upload/v1614908735/Plant_Track/Fiddle_leaf_fig_pjpfcd.jpg" })
Picture.create!({ plant_id: plant19.id, user_id: user1.id, img_url: "https://res.cloudinary.com/benlovesplants89/image/upload/v1614908736/Plant_Track/Peace_Lilly_bp7jn8.jpg" })
Picture.create!({ plant_id: plant20.id, user_id: user1.id, img_url: "https://res.cloudinary.com/benlovesplants89/image/upload/v1614908736/Plant_Track/Oxalis_triangularis_purpurea_c4y8p4.jpg" })
Picture.create!({ plant_id: plant1.id, user_id: user2.id, img_url: "https://res.cloudinary.com/benlovesplants89/image/upload/v1614908738/Plant_Track/PinkPrincess2_cps0ll.png" })
Picture.create!({ plant_id: plant2.id, user_id: user3.id, img_url: "https://res.cloudinary.com/benlovesplants89/image/upload/v1614908737/Plant_Track/scindapsus_treubii_amnu9l.jpg" })
Picture.create!({ plant_id: plant3.id, user_id: user2.id, img_url: "https://res.cloudinary.com/benlovesplants89/image/upload/v1614908738/Plant_Track/Zebra_Basket_Vine2_bniqrf.jpg" })
Picture.create!({ plant_id: plant1.id, user_id: user2.id, img_url: "https://res.cloudinary.com/benlovesplants89/image/upload/v1614908737/Plant_Track/PinkPrincess3_rzcrvm.jpg" })
# Picture.create!({plant_id: plant1.id, user_id: user1.id, img_url: "",})
